[packages]
apt = ["chromium", "chromium-driver", "libnss3", "libatk-bridge2.0-0", "libcups2", "libdrm-dev", "libxkbcommon-x11-0", "libxcomposite1", "libxdamage1", "libxext6", "libxfixes3", "libxrandr2", "libgbm1", "libasound2"]
